# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sugi < Formula
  desc "Terminal UI git client — PRs, AI commits, interactive rebase, bisect, worktrees"
  homepage "https://github.com/Kroszborg/sugi"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kroszborg/sugi/releases/download/v0.2.1/sugi_0.2.1_macOS_x86_64.tar.gz"
      sha256 "3681aefea46312c59efb0285c43805d1c3afd774a9bae97062eef81304b5f62c"

      define_method(:install) do
        bin.install "sugi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kroszborg/sugi/releases/download/v0.2.1/sugi_0.2.1_macOS_arm64.tar.gz"
      sha256 "2f94e32c1aeb0b9af2253c2b1b7368ad54e74944b0a60b9064daef67991acfd9"

      define_method(:install) do
        bin.install "sugi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kroszborg/sugi/releases/download/v0.2.1/sugi_0.2.1_Linux_x86_64.tar.gz"
      sha256 "c4cf5a36174300a08fe887427022f93d80df1c27285451f7e71d5bdd48c9fab2"
      define_method(:install) do
        bin.install "sugi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kroszborg/sugi/releases/download/v0.2.1/sugi_0.2.1_Linux_arm64.tar.gz"
      sha256 "1d3aa2af4040015ddbe498444334ec5b72a13b03bd783bfca4331b7e6cb99a37"
      define_method(:install) do
        bin.install "sugi"
      end
    end
  end

  test do
    system "#{bin}/sugi", "version"
  end
end
