# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sugi < Formula
  desc "Terminal UI git client — GitHub/GitLab PRs, AI commit messages, commit graph"
  homepage "https://github.com/Kroszborg/sugi"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kroszborg/sugi/releases/download/v0.1.1/sugi_0.1.1_macOS_x86_64.tar.gz"
      sha256 "091d3a8eea395e1b7a41e5bc27cadb066256d58fcf0903b6672ef9c7b708c4ba"

      define_method(:install) do
        bin.install "sugi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kroszborg/sugi/releases/download/v0.1.1/sugi_0.1.1_macOS_arm64.tar.gz"
      sha256 "6f8c18f43abcfac37ee782e09481b8a11ed186972d74c2afb264e43dd77c9042"

      define_method(:install) do
        bin.install "sugi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kroszborg/sugi/releases/download/v0.1.1/sugi_0.1.1_Linux_x86_64.tar.gz"
      sha256 "ecadc83a841fc56ddc8f7683f37a47953115bdbc284155366da51e44647e1773"
      define_method(:install) do
        bin.install "sugi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kroszborg/sugi/releases/download/v0.1.1/sugi_0.1.1_Linux_arm64.tar.gz"
      sha256 "c7d69a1a8dc630c00a7af71ca97379a2445bf6453885e405364bcb88272083c6"
      define_method(:install) do
        bin.install "sugi"
      end
    end
  end

  test do
    system "#{bin}/sugi", "version"
  end
end
